metadata:
  name: "guestbook-ui"
apiVersion: "apps/v1"
kind: "Deployment"
spec:
  template:
    metadata:
      labels:
        app: "guestbook-ui"
    spec:
      containers:
      - image: "gcr.io/google-samples/gb-frontend:v5"
        name: "guestbook-ui"
        ports:
        - containerPort: 80
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: "guestbook-ui"
